ci: fix build.yml rubygems-update version
At the time of writing, the latest rubygems-update require ruby >= 3.0.0

Error message reported for build.yml on GHA ci:
```
Run gem update --system
ERROR:  Error installing rubygems-update:
	There are no versions of rubygems-update (= 3.5.4) compatible with your Ruby & RubyGems
	rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
```

This happens when `ruby-version` from matrix is 2.7

At the time of this change, the latest rubygems-update compatible with ruby 2.7 is: 3.4.22

Pinning rubygems-update to 3.4.22 for the GHA ci scope